config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "lists#index"
  resources :lists, only: [ :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :create, :destroy ]
  end
  # resources :bookmarks, only: [ :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, :overview, presence: true
  before_destroy :check_bookmark_count

  private

  def check_bookmark_count
    if Bookmark.where(movie_id: self.id).exists?
        raise ActiveRecord::InvalidForeignKey
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  # def new
  #   @list = List.find(params[:list_id])
  #   @bookmark = Bookmark.new()
  # end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entry
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new()
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Watch List" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Rails Watch List">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="hero-index">
  <nav class="nav-index">
    <%= link_to "moviz", root_path, class: "navbar-logo mx-4" %>
  </nav>
    <div class="hero-index-text">
      <h1>Your place to organize <br>what you wanna see most</h1>
      <%= link_to "Create List", new_list_path, class: "btn-hero" %>
    </div>
</div>

<div class="container mt-4">
  <div class="cards-index">
    <% @lists.each do |list| %>
      <% if list.photo.attached? %>
        <div class="card-index"
        style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, crop: :fill %>')">
          <h2><%= link_to list.name, list_path(list) %></h2>
        </div>
      <% else %>
        <div class="card-index">
          <h2><%= link_to list.name, list_path(list) %></h2>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class=hero-new>
<nav class="nav-new">
      <%= link_to "moviz", root_path, class: "mx-4" %>
</nav>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-6 card-new-form my-4">

      <h1 class="my-2">Create a new list</h1>

      <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Add list", class: "btn btn-hero" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <div class="hero-show"
  style="background-image: linear-gradient(to bottom, rgba(0,0,0,0.2), rgba(0,0,0,1)), url('<%= cl_image_path @list.photo.key, crop: :fill %>')">
    <nav class="nav-show">
      <%= link_to "moviz", root_path, class: "mx-4" %>
    </nav>
    <div class="list-name">
      <h1 class="list-name my-4"><%= @list.name %></h1>
    </div>
  </div>
<% else %>
  <div>
    <h1 class="my-4"><%= @list.name %></h1>
  </div>
<% end %>

<div class="container">
  <%= link_to "Delete this list", list_path(@list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-secondary" %>
  <div class="row align-items-start">
    <div class="col-9">
      <div class="cards">
      <% @list.movies.each do |movie| %>
        <div class="card-custom mx-4">
          <%= image_tag(movie.poster_url) %>
          <div class="lower-card">
            <%= movie.title %>
            <%= link_to "Delete", list_bookmark_path(@list, @list.bookmarks.find_by(movie: movie)), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-secondary" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-3 card-form">
    <h3 class="my-4">Add a movie to this list</h3>
      <%= simple_form_for [ @list, @bookmark ] do |f| %>
      <%= f.input :comment %>
      <%= f.association :movie %>
      <%= f.submit "Add movie to list", class:"btn btn-hero" %>
      <% end %>
    </div>
  </div>
</div>